# This file stores configurations for your Shopify app.

scopes = "write_discounts,write_content,write_script_tags,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects"
